name: autofix.ci

on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
      - run: pnpm lint:fix
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
