name: Clean up PR service images

on:
  pull_request:
    types: [closed]

jobs:
  purge-images:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - config-init
          - egress
          - notifier
          - exporter
          - scraper
    steps:
      - uses: chipkent/action-cleanup-package@v1.0.3
        continue-on-error: true
        with:
          package-name: ${{ github.event.repository.name }}-${{ matrix.target }}
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
